### PR TITLE
Do not fail if association type or producte is missing on Akeneo

### LINKED ISSUE #70: Product associations importer should not fail if the association type or product to associate is missing on Sylius
IMHO it should go ahead without throwing any error. What do you think?

### PR DESCRIPTION
**Pull request by mmenozzi**
Fixes #70

### CODE REVIEW

File: tests/Integration/ProductAssociations/ImporterTest.php [hunk 1]
```diff
@@ -85,7 +85,7 @@ public function it_throws_exception_when_the_product_that_has_being_importer_doe
     /**
      * @test
      */
-    public function it_throws_exception_when_the_product_association_type_does_not_exists_and_it_has_products()
+    public function it_does_not_fail_when_the_product_association_type_does_not_exists_and_it_has_products()
```
Comment (LucaGallinari) [inline tests/Integration/ProductAssociations/ImporterTest.php:88]: "and_it_has_products" could be removed as the check isn't done anymore

**Review by LucaGallinari — APPROVED** [review]
I added a comment for a simple fix but, beside that, it is ready to be merged!
