### PR TITLE
Remove product taxons which are not associated on Akeneo (#45)

### LINKED ISSUE #45: Wrong (?) taxon handling in product import
Here:

https://github.com/webgriffe/SyliusAkeneoPlugin/blob/36d097d7f9aba26ca30028952ec721d428efa544/src/Product/Importer.php#L221-L235

When handling taxons we only add resolved taxons to the product without removing those that were previously associated.

IMHO it's a bug.

### PR DESCRIPTION
**Pull request by mmenozzi**
Fixes #45

### CODE REVIEW

File: src/Product/Importer.php [hunk 1]
```diff
@@ -220,15 +222,29 @@ private function handleChannels(ProductInterface $product, array $productVariant
...
+        $toRemoveTaxonsCodes = array_diff($syliusTaxonsCodes, $akeneoTaxonsCodes);
+
+        foreach ($product->getProductTaxons() as $productTaxon) {
+            $taxon = $productTaxon->getTaxon();
+            Assert::isInstanceOf($taxon, TaxonInterface::class);
+            if (in_array($taxon->getCode(), $toRemoveTaxonsCodes, true)) {
+                $product->getProductTaxons()->removeElement($productTaxon);
+            }
+        }
+        foreach ($toAddTaxons as $toAddTaxon) {
```
Comment (azambon) [inline src/Product/Importer.php:243]: To be more uniform with the previous loop, I would remove the call to filter() at line 229 and replace it with another call to array_diff():

$toAddTaxonsCodes = array_diff($akeneoTaxonsCodes, $syliusTaxonsCodes);

And then here I would change this foreach to iterate on $akeneoTaxons and check with in_array() if the current taxon must be added

Comment (mmenozzi) [reply src/Product/Importer.php:243]: This was my first implementation but when adding taxons we need the actual Taxon objects because we have to set them to the ProductTaxon objects. Having only the taxon code force to do another search to get the taxon object.

**Review by LucaGallinari — APPROVED** [review]

**Review by lruozzi9 — APPROVED** [review]

File: src/Product/Importer.php (hunk 1 above)
Comment (mmenozzi) [reply src/Product/Importer.php:243]: I think it's a matter of preference. I'd prefer to avoid the check on which are the taxons to add instead of having uniform array_diff.
