### PR TITLE
Fix immutable slug incremental bug (#78)

### LINKED ISSUE #78: Error on generating slug for three or more products with same name
There is a BUG in ImmutableSlugValueHandler on generating slug for a product with the same name as another.
For example:
If I have three products named "T-shirt banana", the importer will generate a "t-shirt-banana" slug for the first one, "t-shirt-banana-1" for the second one, and "t-shirt-banana-1-2" for the third instead of "t-shirt-banana-2".

### PR DESCRIPTION
**Pull request by lruozzi9**
This will fix #78

### CODE REVIEW

File: src/ValueHandler/ImmutableSlugValueHandler.php [hunk 1]
```diff
@@ -131,19 +131,21 @@ private function getDeduplicatedSlug(
         if ($increment > self::MAX_DEDUPLICATION_INCREMENT) {
             throw new \RuntimeException('Maximum slug deduplication increment reached.');
         }
+        $slugToCheck = $slug;
+        if ($increment > 1) {
```
Comment (mmenozzi) [inline src/ValueHandler/ImmutableSlugValueHandler.php:135]: Am I wrong or in this way the slug-1 will never be returned?

File: src/ValueHandler/ImmutableSlugValueHandler.php [hunk 2]
```diff
@@ -131,19 +131,21 @@ private function getDeduplicatedSlug(
         if ($increment > self::MAX_DEDUPLICATION_INCREMENT) {
             throw new \RuntimeException('Maximum slug deduplication increment reached.');
         }
+        $slugToCheck = $slug;
```
Comment (mmenozzi) [inline src/ValueHandler/ImmutableSlugValueHandler.php:134]: I'd rename this variable $deduplicatedSlug

**Review by mmenozzi — CHANGES_REQUESTED** [review]

File: src/ValueHandler/ImmutableSlugValueHandler.php (hunk 2 above)
Comment (lruozzi9) [reply src/ValueHandler/ImmutableSlugValueHandler.php:134]: Are you sure? We still don't know if this slug is duplicated. Wouldn't IncrementalSlug be better?

Comment (mmenozzi) [reply src/ValueHandler/ImmutableSlugValueHandler.php]: Yes I am. At the time of the first assignment we don't know if it's deduplicated but then the variable is written again with a deduplicated slug and is returned. So that variable will become for sure the deduplicated slug.

**Review by mmenozzi — APPROVED** [review]
